#define THROTTLE_PWM_PIN 5
#define THROTTLE_CHANNEL 1

#define STEERING_PWM_PIN 6
#define STEERING_CHANNEL 2
#define STEERING_MIN 50
#define STEERING_MAX 130

#define WINCH_1_PWM_PIN 7
#define WINCH_1_CHANNEL 3
#define WINCH_2_PWM_PIN 8
#define WINCH_2_CHANNEL 4

#define HEADLIGHT_PIN 9
#define HEADLIGHT_CHANNEL 5

#define BLINKER_LEFT_PIN 10
#define BLINKER_RIGHT_PIN 20
#define BRAKE_LIGHT_PIN 21

#define STATUS_LED_PIN 2

#define UPDATE_LOOP_FREQUENCY_HZ 250

#define CRSF_BAUDRATE 420000
#define CRSF_RX_PIN 1
#define CRSF_TX_PIN 0
