#define THROTTLE_PWM_PIN 5
#define THROTTLE_CHANNEL 0

#define STEERING_PWM_PIN 6
#define STEERING_CHANNEL 1

#define WINCH_1_PWM_PIN 7
#define WINCH_2_PWM_PIN 8
#define WINCH_CHANNEL 2

#define HEADLIGHT_PIN 9
#define HEADLIGHT_CHANNEL 3

#define BLINKER_LEFT_PIN 10
#define BLINKER_RIGHT_PIN 20
#define BRAKE_LIGHT_PIN 21

#define UPDATE_LOOP_FREQUENCY_HZ 250